### ISSUE TITLE
robots: don't use dor-fetcher service

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#10]
dor-fetcher service is being phased out.  Anywhere the code uses it, is there a diff way to get the info?   If stumped, talk to Laney.

**Comment by drh-stanford** [comment]
The robots don't seem to use the dor-fetcher services -- as far as I can tell, it's a `was-registrar` only problem. See https://github.com/sul-dlss/was-registrar/issues/29
