### ISSUE TITLE
reduce bluepill log growth

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#12]
the bluepill logs can get pretty big.  Two ideas:
- turn down the bluepill logging level
- rotate and discard the logs

**Comment by drh-stanford** [comment]
See https://github.com/sul-dlss/robot-controller/pull/45

**Comment by ndushay** [comment]
I'll put it in the log rotation list

**Comment by ndushay** [comment]
I'm closing this ticket;  it should be addressed via #31  (log rotation for robot suite logs)
