### ISSUE TITLE
exercise all robots in production

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/was_robot_suite#14]
Not all of the robots in production have had items fed through them yet. Here is the list of robots and a checkmark if they have processed items successfullly:

wasCrawlDisseminationWF:
 - [x] cdx-generator
 - [x] cdx-merge-sort-publish
 - [x] path-indexer

wasCrawlPreassemblyWF:
  - [x] build-was-crawl-druid-tree
  - [x] content-metadata-generator
  - [x] desc-metadata-generator
  - [x] end-was-crawl-preassembly
  - [x] metadata-extractor
  - [x] technical-metadata-generator

wasDisseminationWF:
  - [x] start-special-dissemination

wasSeedDisseminationWF:
  - [x] update-thumbnail-generator

wasSeedPreassemblyWF:
  - [x] build-was-seed-druid-tree
  - [x] content-metadata-generator
  - [x] desc-metadata-generator
  - [x] end-was-seed-preassembly
  - [x] thumbnail-generator

**Comment by ndushay** [comment]
it would be awesome if @nullhandle were able to run a seed and a crawl through the whole ingest process, start to finish.
