### ISSUE TITLE
Description in workflow definition incomplete

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/was_robot_suite#18]
The description for the cdx-merge-sort-publish step is just "M" in the workflow definition. We can fix this by editing the workflow definition in DOR (and put the updated definition into the DOR prod, test, and dev environments).

**Comment by ndushay** [comment]
to deploy, we will need to manually copy the XML change from #35 into the DOR workflow objects in -prod, -test, and -dev:

**Comment by drh-stanford** [comment]
Updated DOR workflow objects in DOR  -dev, -test, and -prod
