### ISSUE TITLE
robots: Add nagios check to confirm robots are running

### ISSUE THREAD

**Issue by eefahy** [sul-dlss/was_robot_suite#19]
We currently only have one log check in nagios for this suite: https://sul-nagios-prod.stanford.edu/nagios/cgi-bin//extinfo.cgi?type=2&host=sul-robots3-prod&service=sul-robots3-prod%3Anagios-prod+check_log_was_robot_suite which only tells us that there is not the string ERROR in the logs however it does not tell us if the robots are indeed running.

**Comment by drh-stanford** [comment]
There should be a `was_robot_suite/shared/log/verify.log` - it normally just says "OK" and it runs every 5 mins from cron to see whether the robots are running.

Is that sufficient? It's what we do for common-accessioning, for example.

**Comment by ndushay** [comment]
use the sul-was-support list  when approp for notifications;  note SLAs for prod, stage, dev VMs ...

**Comment by ndushay** [comment]
use the sul-was-support list  when approp for notifications;  note SLAs for prod, stage, dev VMs ...

**Comment by drh-stanford** [comment]
I added a PR #45 for this. The other changes will have to be done in the puppet repo

**Comment by ndushay** [comment]
when done in puppet, update devops docs.  @drh-stanford  is this something we should do a PR for or should it be a SAR ticket or ...

**Comment by ndushay** [comment]
be sure to migrate checks off of newcaprica (`sul-robots3-prod-was-robots-suite-check`) and update devops checklist
