### ISSUE TITLE
create VMs specific to was robots

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#20]
1.  make VMs (prod, stage, dev) for was robots  (`was-robots1-{prod,stage,dev}`), with only the mount points the was robots need

2.  remove the web archiving specific mount points from the other robots (simplify them)

from sul-dlss/web-archiving#3:
>There's constant confusion as to which sul-robots* machines the WAS robot suites run on. So this ticket is to create was-robot VMs and migrate the WAS robot suites from the sul-robots* machines onto these new VMs.

The other item is that the was robots require Java whereas other DLSS robots do not, so we can remove java from the other robots machines.

**Comment by ndushay** [comment]
SAR-3325 ticket already created for dedicated was-robots machine

**Comment by ndushay** [comment]
be sure to change:
- nagios to look for robots in new place
- log rotation from new place

**Comment by tallenaz** [comment]
-dev should be done today

**Comment by drh-stanford** [comment]
i've deployed -dev and -stage already and disabled the was robots on the old sul-robots boxes. waiting for the shared_configs clone to deploy to -prod.

**Comment by drh-stanford** [comment]
Note that (unfortnately) the sul-robots* VMs will need to mount the `/web-archiving-stacks` mounts. This is due to the fact that common-accessioning is the actual process that shelves the WARC files.

**Comment by ndushay** [comment]
update the devops docs before closing this, please.
