### ISSUE TITLE
support non-ascii characters in seed URLs

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/was_robot_suite#213]
[druid:vf219gh9697](https://argo.stanford.edu/view/druid:vf219gh9697) is the seed object for the following URL:

https://fr.wikipedia.org/wiki/Liste_de_sondages_sur_l'élection_présidentielle_française_de_2017

This item is not showing any snapshots [on the purl](https://purl.stanford.edu/vf219gh9697) and the item has the following error in the wasSeedDisseminationWF:

```
update-thumbnail-generator : URI must be ascii only "https://was-thumbnail-prod.stanford.edu/api/seed/create?druid=vf219gh9697&uri=https://fr.wikipedia.org/wiki/Liste_de_sondages_sur_l'\u00E9lection_pr\u00E9sidentielle_fran\u00E7aise_de_2017"
```

**Additional context**
If you go directly to SWAP with the correct URL, you do get snapshots:
https://swap.stanford.edu/*/https://fr.wikipedia.org/wiki/Liste_de_sondages_sur_l'%C3%A9lection_pr%C3%A9sidentielle_fran%C3%A7aise_de_2017

It looks like the URL is being truncated on the purl at the first apostrophe.

**Comment by jcoyne** [comment]
@andrewjbtw I think the problem here is that the source data is an invalid URI.  URIs are only allowed to have ascii characters.  The one you have provided is canonically written: https://fr.wikipedia.org/wiki/Liste_de_sondages_sur_l'%C3%A9lection_pr%C3%A9sidentielle_fran%C3%A7aise_de_2017

**Comment by andrewjbtw** [comment]
I guess the question then is how to edit the object to correct the URL. Maybe if I edit the descriptive metadata.

**Comment by jcoyne** [comment]
@andrewjbtw yes, let's do that. Can we figure out how to avoid getting the bad data in the system in the first place?

**Comment by andrewjbtw** [comment]
I see that I fixed this object last year when we were getting web archive accessioning back on track. It turned out the proper place to enter the URL for thumbnail generation is in the identityMetadata objectLabel. After thumbnail generation, the URL is canonically stored in the descMetadata. This seems to be an artifact of how accessioning worked when this workflow was first created, where descMetadata didn't get created until later in the process, post-registration.
