### ISSUE TITLE
plan to improve performance of crawl diss cdx-merge-sort-publish step

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#22]
The main CDX file is now 106G.  It takes about 20 min to add a druid's cdx entries to the main file.

(see also jira DEVQUEUE-79)

How might this be impacted by upgrading OpenWayback code?  Would CDX format change?

Should we do the giant sort via a database or Solr and then export back to a file?

Is it reading and writing over NFS mounts that are tanking performance?   If we move the WAS robots to their own VM, can we change how we are accessing the web-archiving-stacks mount point?  Where else is the mount point used?

Ahmed suggested:
> Merging and sorting CDX files is not scalable. When the CDX file grows more, the sorting step will take longer time.
> Suggested solution:
>    Sort each new CDX file individually.
>    Merge the sorted CDX with the main cdx file.

unfortunately, the bulk of the time is spent merging the two sorted files together.

drh-stanford suggests:
>We might be able to use tmpfs on the VM to improve the performance some -- it's currently ~4GB. -- or use the -S flag to specify a larger in memory buffer. The sort command is using the -u and -m flags.

replaces sul-dlss-deprecated/was-crawl-dissemination/issues/14

**Comment by drh-stanford** [comment]
we discussed this at length and the next step is to remeasure the performance characteristics to see whether we're CPU or IO/Network bound (we suspect the latter).

the current proposal is to do the individual CDX sorting and the merge into the master CDX file asynchronously from the workflow itself. this would allow us to run daily (or whatever interval) merges for the big CDX file and avoid the performance hit of doing the merge for every druid.

the pipeline is (a) cdx-generator -> (b) sort all CDX files into single file -> (c) merge that file into the master CDX file -> (d) rename the temporary master CDX to the final location. steps (b) and (c) and (d) could be done together asynchronously in a single "transaction". Running this via cron would work.

if this proposal worked, then we'd have other bottlenecks in the pipeline, notably cdx-generator and metadata-extractor. we could likely parallelize them by running multiple robots for each of those steps and tune the CPU/memory on the VM.

**Comment by ndushay** [comment]
Note email I sent Dec 8 with subject "web-archiving WF robots: which parts are slow?" that calls out 4 workflow steps that can be very slow:

1.  CrawlDisseminationWF_cdx-merge-sort-publish
2.  wasCrawlDisseminationWF_cdx-generator  -- inconsistent.  Possibly due to varying numbers of WARC files associated with a druid?
3.  wasCrawlPreassemblyWF_metadata-extractor -- inconsistent.   Not sure if it could be related to numbers of WARC files.
4.  wasCrawlPreassemblyWF_build-was-crawl-druid-tree:  -- inconsistent.   Likely related to number of WARC files, as they are copied to druid tree.

**Comment by drh-stanford** [comment]
A couple proposal writeups are here: https://github.com/sul-dlss/web-archiving/wiki/Workflow-Pipeline

**Comment by ndushay** [comment]
so is this ticket complete?  We have a plan, and we have the work ticketed, yes?  Close ticket if you agree.

**Comment by drh-stanford** [comment]
yes, now being implemented in https://github.com/sul-dlss/was_robot_suite/issues/47
