### ISSUE TITLE
reduce latency of crawls going thru workflow steps

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#23]
it tends to get bogged down in cdx-merge-sort-publish step.  Could we load balance for this part?  Or can we improve performance single threaded?  See #22

**Comment by ndushay** [comment]
more info in my emails of Dec 8 and Dec 12;  it is actually 4 steps that tend to be slow and we are analyzing them and trying to come up with solutions individually.

**Comment by lmcglohon** [comment]
Superceded by #22, #36, #38
