### ISSUE TITLE
thumbnail_generator_service: Errno::ENOENT: No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/was_robot_suite#234]
See https://app.honeybadger.io/projects/51141/faults/64372052

This is occurring when phantom fails to create a thumbnail, but fails to return an error.

This seems to happen with some URLs, but not others:
* Works: phantomjs rasterize.js https://swap.stanford.edu/20180515215226/http://2hj.org/ test.png
* Doesn't work: phantomjs rasterize.js https://swap.stanford.edu/19900101120000/http://www.zennorin.jp/ test.png

I'd suggest that replacing phantomjs (which is no longer supported) is necessary.

**Comment by jcoyne** [comment]
Curiously, when I try to grab these screenshots with Chrome, I only get the swap header bar for: https://swap.stanford.edu/19900101120000/http://www.zennorin.jp/
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --headless --screenshot https://swap.stanford.edu/19900101120000/http://www.zennorin.jp/
```
![screenshot](https://user-images.githubusercontent.com/92044/83798791-65082c00-a66a-11ea-8275-066f9803fd44.png)





but https://swap.stanford.edu/20180515215226/http://2hj.org/ is fine:
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --headless --screenshot https://swap.stanford.edu/20180515215226/http://2hj.org/
```
![screenshot](https://user-images.githubusercontent.com/92044/83798739-4efa6b80-a66a-11ea-9f2b-deadf8089503.png)

**Comment by andrewjbtw** [comment]
I believe this is now fixed with the switch to headless chrome for the seed preassembly thumbnails.
