### ISSUE TITLE
Replace PhantomJS for creating thumbnail

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/was_robot_suite#236]
PhantomJS is no longer supported and does not work correctly.

See #234

**Comment by jcoyne** [comment]
This looks easy with chrome:
https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a

We could also do it with firefox, but it has a bug where it won't follow redirects.

**Comment by jcoyne** [comment]
Depends on https://github.com/sul-dlss/operations-tasks/issues/2265
