### ISSUE TITLE
wasSeedPreassembly should create/use MODS label "Archived website" instead of "Archived site"

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/was_robot_suite#257]
**Describe the issue**
When accessioning a web archive seed, the wasSeedPreassembly workflow generates an initial MODS record that points to the SWAP URL for the seed:

```xml
<location displayLabel="Archived site">
    <url>https://swap.stanford.edu/*/https://www.j-oled.com/oled/</url>
</location>
```
The wasSeedPreassembly workflow uses this data to generate the thumbnail.

Once a web archive seed has been accessioned, the web archivist (or metadata staff, or a curator) imports new MODS that uses slightly different XML to point to the archived site:

```xml
  <location>
    <url usage="primary display">http://purl.stanford.edu/gb089bd2251</url>
    <url displayLabel="Archived website">https://swap.stanford.edu/*/http://naca.central.cranfield.ac.uk/</url>
  </location>
```

The sul-embed viewer for web archive seeds relies on this data for display and shows an error if the MODS doesn't conform to this structure.

These two `<location>` blocks should be made consistent. Since we ultimately want the second block displayed on the purl, I propose that we change the wasSeedPreassembly workflow to create and use the second `<location>` block from the start.

**User Impact**
Web archive seeds that have been accessioned but have not yet had their MODS updated show errors in the embed viewer on the purl.

**Additional context**
Example seed with auto-generated MODS:
https://argo.stanford.edu/view/druid:bd812qv1215

Example seed after MODS update:
https://argo.stanford.edu/view/gb089bd2251

**In the long run**
We should find some other part of the public XML to store this URL as it should never change. Putting it in the MODS means that a new metadata update, or an update to the template used for web archives, could unintentionally break things at any time.

**Comment by peetucket** [comment]
I think this particular issue may just require the small change in this PR: #258

**Comment by andrewjbtw** [comment]
I think the thumbnail-generator step (and maybe other steps?) looks for the URL generated by desc-metadata-generator, so there might be an additional corresponding change if it needs to parse the MODS rather than find that value some other way.

**Comment by peetucket** [comment]
ok, just noticed there is a fixture that needs to be updated too

**Comment by peetucket** [comment]
I'm not seeing any other references that url (in descMetadata) in this particular codebase, unless I am missing something
