### ISSUE TITLE
Improve error handling during thumbnail generation

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/was_robot_suite#267]
**Describe the bug**

e.g.:
```
RuntimeError: Thumbnail for druid druid:sy635yd1125 and http://www.g20.org/ can't be generated.
 Navigation timeout of 30000 ms exceeded
```

```
[PROJECT_ROOT]/lib/was_seed_preassembly/thumbnail_generator_service.rb:18 :in `rescue in capture_thumbnail`
[PROJECT_ROOT]/lib/was_seed_preassembly/thumbnail_generator_service.rb:14 :in `capture_thumbnail`
[PROJECT_ROOT]/robots/was_seed_preassembly/thumbnail_generator.rb:11 :in `perform`
[GEM_ROOT]/gems/lyber-core-6.1.1/lib/lyber_core/robot.rb:58 :in `block in work`
/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/benchmark.rb:308 :in `realtime`
[GEM_ROOT]/gems/lyber-core-6.1.1/lib/lyber_core/robot.rb:56 :in `work` 
```

the druid for which this error most recently occurred has encountered it 11 times (`thumbnail-generator` step of `wasSeedPreassemblyWF`).

see
* https://app.honeybadger.io/projects/51141/faults/66136138
* https://argo.stanford.edu/view/sy635yd1125 (still in error on the `thumbnail-generator` step)
* https://argo.stanford.edu/view/vf219gh9697 (not in an error state because the `thumbnail-generator` step was skipped, though a thumbnail must've been provided by other means, since the object has one now)
* https://argo.stanford.edu/view/jq428fm3720 (ditto)
* https://argo.stanford.edu/view/fd703nb8583 (ditto)
[...see honeybadger for more druids...]

**User Impact**

would seem to prevent automatic thumbnail capture for some web pages

**To Reproduce**

not sure

**Expected behavior**

a thumbnail is captured by the robot

**Screenshots**

![Screen Shot 2020-09-03 at 10 47 21 PM](https://user-images.githubusercontent.com/7741604/92204182-c4c3ce00-ee37-11ea-9b0b-3cb10dac4800.png)

**Additional context**

i'm not the most familiar with this codebase, so apologies if this error report isn't as detailed as desired (just capturing alerts from honeybadger as first responder).

**Comment by edsu** [comment]
In workcycle planning on 5/16 we discussed this problem and decided that timeout errors should be caught, and result in a `missing.jp2` being written instead of the thumbnail. This will:

1. Allow the workflow to proceed instead of failing
2. Allow a scheduled report to be able to notice thumbnails that are in need of attention.

Really any unexpected exceptions during thumbnail generation should result in`missing.jp2` being written instead.

**Comment by mjgiarlo** [comment]
#81 is a more specific instance of the behavior in this ticket, but we still do want improvements to error handling writ large.

**Comment by mjgiarlo** [comment]
We need to discuss what improvements are included in this work so the developer taking this on knows when they are done.
