### ISSUE TITLE
merge-sort-publish step can't be repeated if it failed

### ISSUE THREAD

**Issue by lmcglohon** [sul-dlss/was_robot_suite#27]
_From @aalsum on January 30, 2015 18:52_

This robot step is modifying the file structure which can't be reversed if there is any failure happened in the middle. My suggestion is to divide it into steps that can be repeated.

_Copied from original issue: sul-dlss-deprecated/was-crawl-dissemination#4_

**Comment by lmcglohon** [comment]
_From @ndushay on December 7, 2016 2:40_

if the merges remove dups, it should be repeatable ...

**Comment by lmcglohon** [comment]
_From @ndushay on December 8, 2016 1:38_

I don't understand why this would be true.  If the druid/WARC specific cdx files hang around, then we can repeat this.  In fact, if we can generate new CDX files from preserved WARC files, then we don't even need the cdx files to repeat ...

**Comment by ndushay** [comment]
spoke to @nullhandle and @drh-stanford and we agree we think this is NOT an issue.
