### ISSUE TITLE
is replacing openwayback cdx file enough for openwayback to know about new WARCs?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#28]
are we sure that just putting in a new main cdx file means the openwayback software knows about the new data inside?

If not, can we export the data to the wayback machine on a nightly process.

**Comment by ndushay** [comment]
@nullhandle  says "yes" - it reads from the file for every lookup.

**Comment by drh-stanford** [comment]
i had looked into this a bit yesterday, and it was confusing but there's a plugin API for how to deal with CDX files. For example, see https://github.com/iipc/openwayback/wiki/WatchedCDXSource:-Dynamically-Adding-CDX-Indexes

We're using a very simple configuration that points the instance to a single CDX file. For details on all the configuration options see https://github.com/iipc/openwayback/wiki/How-to-configure#configuring-wayback-to-find-cdxs

**Comment by ndushay** [comment]
closing this ticket;  we should open a new one for switching to WatchedCDXSource ...
