### ISSUE TITLE
swap/robots: does upgrading openwayback change CDX format or processing?

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#29]
@nullhandle thinks no.

**Comment by drh-stanford** [comment]
For where we install the jars we need to run CDX indexing see https://github.com/sul-dlss/was_robot_suite/blob/master/config/deploy.rb#L47-L54

**Comment by drh-stanford** [comment]
Also see our fork of the code here https://github.com/sul-dlss/openwayback

**Comment by edsu** [comment]
We are no longer using openwayback, so the answer to this is no longer relevant for us.
