### ISSUE TITLE
robots: implement log retention policy

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/was_robot_suite#31]

**Comment by lmcglohon** [comment]
Nicholas and I agree that the log retention policy should be thirty days

**Comment by ndushay** [comment]
filed SAR-3341

**Comment by ndushay** [comment]
updated docs sul-dlss/DevOpsDocs/pull/118

**Comment by ndushay** [comment]
Kam just did SAR-3341;  confirm it works, then close this

**Comment by ndushay** [comment]
@tallenaz  can you confirm we are rotating ALL the logs in was_robot_suite/shared/logs  on the new prod and stage VMs?

**Comment by tallenaz** [comment]
@ndushay yes, all logs are being rotated
