### ISSUE TITLE
robots: Investigate the W lane

### ISSUE THREAD

**Issue by lmcglohon** [sul-dlss/was_robot_suite#40]
There is a "W" lane in the robots environment that is supposed to give Web Archiving priority for accessioning, but at first glace it doesn't look like it's configured correctly. This ticket is to investigate the current configuration and identify whether we need to update it. It affects common-accessioning and the was-robot-suite at a minimum.

**Comment by ndushay** [comment]
@drh-stanford  now that we are going to separate VMs, is the W lane even in play?  Pleas close this issue if it's now moot.

**Comment by drh-stanford** [comment]
The W lane is pervasive as accessionWF and disseminationWF use it. sul-robots3 common-accessioning specifically is only working on jobs in the W lane. I don't think this is necessary but I might be wrong, so this ticket should stay open.

**Comment by drh-stanford** [comment]
I've dug into the current production configuration of the lanes and documented it here:

https://github.com/sul-dlss/robot-master/wiki/FAQ:-More-advanced-usage#what-are-lanes-how-are-we-using-them-in-production

The W lane is explicilty set as the priority lane in the wasCrawlPreassemblyWF here -- https://github.com/sul-dlss/was_robot_suite/blob/master/robots/wasCrawlPreassembly/end_was_crawl_preassembly.rb#L14

**Comment by drh-stanford** [comment]
All of the lane allocation is done via configuration files that AFAIK are not in any repo, just on the VMs themselves. So, the sul-robots* are not using shared_configs but they should be all the same for 1,2,3,4,5. i created the beginning of a shared_config for these VMs here: 

https://github.com/sul-dlss/shared_configs/tree/sul-robots-prod/common-accessioning/config/environments

**Comment by drh-stanford** [comment]
I've fixed production and test to no longer use the W lane. This issue will be fixed when the shared_config PRs are merged.
