### ISSUE TITLE
Complete removal of wasMetadataExtractor from application

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was_robot_suite#438]
Depends on outcome of research in #436 and #437. Remove the metadata-extractor steps and the wasMetadataExtractor.jar dependency from wasCrawlPreassembly. 

1. Remove download from [config/deploy.rb](https://github.com/sul-dlss/was_robot_suite/blob/7b52a00cda585796412b34bf9a9af74cb1882473/config/deploy.rb#L41) 
2. Deprecate repo for wasMetadataExtractor
3. Remove from sul-ci-prod (Jenkins)

**Comment by lwrubel** [comment]
wasMetadataExtractor was removed from metadata-extractor step with https://github.com/sul-dlss/was_robot_suite/pull/442. metadata-extractor still is a step, just without the Java library. Will update issue title to reflect this. 

The remaining work on this issue is to remove [WASMetadataExtractor from sul-ci-prod](https://sul-ci-prod.stanford.edu/job/SUL-DLSS/job/WASMetadataExtractor/) and then move the https://github.com/sul-dlss/WASMetadataExtractor repo to sul-dlss-deprecated.

**Comment by lwrubel** [comment]
@jcoyne, @cbeer suggested removing the Jenkinsfile from the repo. Is that something you could try?

**Comment by lwrubel** [comment]
There's a Jenkinsfile in the moved-to-deprecated wasMetadataExtractor repo, but I think you're saying that Jenkins wouldn't be able to find it now that it's moved, so no point also removing the file at this point? Although when I click on the GitHub link from within Jenkins, it takes me to the deprecated repo so it seems connected still somehow. I'm wondering if I just don't have rights to see a "delete pipeline" option.

**Comment by mjgiarlo** [comment]
I've removed the Jenkinsfile from this repo (required unarchiving and re-archiving), so either that will remove it from sul-ci-prod (great!) or it won't (oh well). Closing this issue for now.
