### ISSUE TITLE
Remove technical-metadata step from wasCrawlPreassembly

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was_robot_suite#444]
Based on #437, remove the technical-metadata step in the workflow, confirming that technical metadata is still generated as needed in the regular accessionWF step.

**Comment by jcoyne** [comment]
@lwrubel do you mean the `technical-metadata-generator` step?

**Comment by lwrubel** [comment]
Yes, that should be `technical-metadata-generator`.

**Comment by lwrubel** [comment]
@justinlittman just checking--are you also working on this as part of https://github.com/sul-dlss/workflow-server-rails/pull/560?

**Comment by justinlittman** [comment]
Yes, see https://github.com/sul-dlss/workflow-server-rails/pull/560

**Comment by jcoyne** [comment]
@justinlittman is there a reason that's a draft and not a PR?

**Comment by justinlittman** [comment]
Yes, because I was waiting for @andrewjbtw to review in stage (which he has done). Undrafting.
