### ISSUE TITLE
Remove cdx-related steps from wasCrawlDissemination workflow

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was_robot_suite#451]
After we are no longer using openwayback, remove the following steps from wasCrawlDissemination:

- cdx-generator
- cdx-sort-merge-publish

These will no longer be needed because there will be steps created in https://github.com/sul-dlss/was_robot_suite/issues/449 that provide the equivalent workflow steps with cdxj files for pywb. 

workflow-server-rails will also need to be updated to show only the following steps in wasCrawlDissemination:
- warc-extractor
- cdxj-generator
- cdxj-merge

This ticket should not be completed until we are on pywb in production and no longer need to the option to fall back to openwayback.

**Comment by mjgiarlo** [comment]
This is a cleanup task after we decommission openwayback.

**Comment by mjgiarlo** [comment]
This is high priority for the non-critical pywb epic.

**Comment by aaron-collier** [comment]
@lwrubel / @mjgiarlo not sure this is captured yet, but we'll also want to update https://github.com/sul-dlss/was_robot_suite/blob/main/config/deploy.rb#L42 to remove the download of the openwayback jar, etc.

**Comment by mjgiarlo** [comment]
@aaron-collier good call, yes, let's include that in scope of this ticket.

**Comment by lwrubel** [comment]
Updated the ticket description to reflect that we added a warc-extractor step that needs to be kept and removed the part about changing path-indexer since we've since decided to remove that step altogether (#492).
