### ISSUE TITLE
Add step to wasCrawlDissemination to handle WACZ files

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was_robot_suite#457]
This ticket is to support accessioning of WACZ files that will have been registered via one-time accessioning in WAS-Registrar-App. The shelve step in the accessionWF will have already have put the WACZ file in `/web-archiving-stacks` and the sdr-ingest-transfer step will have sent the WACZ file to preservation. 

Add a new step to the beginning of wasCrawlDisseminationWF, called get-warcs-from-wacz (open to better names, this is what is coming to mind now). It should:

1) Look for .wacz files in the `/web-archiving-stacks/data/collections/<collection-id>` dir. Extract the .warc.gz files from the .wacz file. In a WACZ, the warcs are gzipped and are in the `archive` directory.  (e.g. `unzip example.wacz archive/*.warc.gz -d <path>`)
2) Delete the .wacz file. 
2) Carry on with the workflow to index the warcs. 

To complete this work, you'll also need to update workflow-server-rails to have this new step in the wasCrawlDisseminationWF.

**Comment by justinlittman** [comment]
Alternatively, you could extract just the WARC file (instead of unzipping all files) and then delete the WACZ file. That might simplify the cleanup logic a bit.

**Comment by lwrubel** [comment]
Thanks, @justinlittman. I've updated the ticket description to use this approach and added more detail.

**Comment by lwrubel** [comment]
This will be easier to work on once one-time accessioning via WRA is merged and deployed.

**Comment by andrewjbtw** [comment]
There's a potential problem here in that since the wasDisseminationWF runs after accessionWF, the files will not be there. The accessionWF cleans them up after depositing to preservation as it's usually the last step in an accessioning job. 

One possibility would be to retrieve the files from preservation but that could add processing time.

**Comment by lwrubel** [comment]
The shelve job puts them on web-archiving-stacks early in accessionWF, so these operations would happen on the WACZ file that has been put there. Or is there something I'm not understanding about the workflow?

**Comment by andrewjbtw** [comment]
You're right - I forgot the order in which we decided to do things.
