### ISSUE TITLE
cdxj-indexer not found error

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was_robot_suite#468]
When doing a one-time registration via the WRA branch https://github.com/sul-dlss/was-registrar-app/pull/468, was_robot_suite logs an error with the cdxj-generator step:

`Error: cdxj-generator : Error in extracting CDXJ with command: cdxj-indexer /web-archiving-stacks/data/collections/bc778pm9866/th/153/yt/3611/apod.warc.gz --output /web-archiving-stacks/data/indexes/cdxj_working/druid:th153yt3611/apod.warc.cdxj --sort --post-append 2>> log/cdx_indexer.log pid 1471664 exit 127 `

https://argo-stage.stanford.edu/view/druid:th153yt3611

From `~/was_robot_suite/current/log/cdx_indexer.log`:

`sh: 1: cdxj-indexer: not found`

**Comment by lwrubel** [comment]
cdxj-indexer is installed on the VM. When on the VM as the `was` user, `cdxj-indexer -h` works.

`which cdxj-indexer` shows `/opt/app/was/.local/bin/cdxj-indexer`

**Comment by edsu** [comment]
The resque seems to run as `was` too?

```
was@was-robots1-stage:~$ ps -ef |grep resque
was      1465536       1  0 11:24 ?        00:00:03 resque-pool-master[20220613182344]: managing [1465817, 1465818, 1465819, 1465820, 1465821, 1465822]
was      1465817 1465536  0 11:24 ?        00:00:02 resque-2.2.1: Waiting for wasCrawlPreassemblyWF_default,wasDisseminationWF_default,wasSeedDisseminationWF_default,wasSeedPreassemblyWF_default
was      1465818 1465536  0 11:24 ?        00:00:02 resque-2.2.1: Waiting for wasCrawlPreassemblyWF_default,wasDisseminationWF_default,wasSeedDisseminationWF_default,wasSeedPreassemblyWF_default
was      1465819 1465536  0 11:24 ?        00:00:02 resque-2.2.1: Waiting for wasCrawlPreassemblyWF_default,wasDisseminationWF_default,wasSeedDisseminationWF_default,wasSeedPreassemblyWF_default
was      1465820 1465536  0 11:24 ?        00:00:02 resque-2.2.1: Waiting for wasCrawlPreassemblyWF_default,wasDisseminationWF_default,wasSeedDisseminationWF_default,wasSeedPreassemblyWF_default
was      1465821 1465536  0 11:24 ?        00:00:02 resque-2.2.1: Waiting for wasCrawlPreassemblyWF_default,wasDisseminationWF_default,wasSeedDisseminationWF_default,wasSeedPreassemblyWF_default
was      1465822 1465536  0 11:24 ?        00:00:01 resque-2.2.1: Waiting for wasCrawlDisseminationWF_default
```

I wonder it runs with a different environment though? I see that `/opt/app/was/.local/bin` is set via the shell configuration in `/opt/app/was/.profile` which may not apply to resque jobs?
