### ISSUE TITLE
Test thumbnail generation with pywb

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was_robot_suite#472]
Test and confirm that thumbnails are created with the current wasSeedPreassembly workflows using to `Settings.was_seed.wayback_uri = "http://was-pywb-stage.stanford.edu"`

Create further tickets depending on the outcome of testing.

**Comment by peterchanws** [comment]
The site appears here https://was-pywb-prod.stanford.edu/was/20111010230027/http://aaastop.stanford.edu/index.html

**Comment by peterchanws** [comment]
This thumbnail looks fine https://argo-stage.stanford.edu/view/druid:rr544gq9298

**Comment by peterchanws** [comment]
This looks fine as well https://argo-stage.stanford.edu/view/druid:vh998hn4533

**Comment by edsu** [comment]
I think we've confirmed that the happy path for thumbnail generation is working. But we still have work to do to make it more reliable. Should we call this ticket done?

**Comment by lwrubel** [comment]
Closing this issue on testing of thumbnail generation, since we've verified the workflow is working. Other tickets will address specific issues (e.g. not found or timeout).
