### ISSUE TITLE
Audit path-index.txt for completeness

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was_robot_suite#477]
Every filename in the cdxj indexes (level0-3.cdxj) should be listed in the path-index.txt to avoid unintended pywb playback errors. 

The filenames are in each line's JSON block, associated the `filename` key:
`cn,org,zjredcross)/3wr/ps/webdisk/1/upload/pdf/20170505083842681.pdf 20200424061217 {"url": "http://www.zjredcross.org.cn//3wr/ps/webDisk/1/upload/PDF/20170505083842681.pdf", "mime": "application/pdf", "status": "200", "digest": "sha1:PPRHWFTF7P3CF2FFWX6LKFHLCVJUTJY5", "length": "302926", "offset": "556977041", "filename": "ARCHIVEIT-5425-CRAWL_SELECTED_SEEDS-JOB1138864-SEED2203381-20200423074711674-00000-h3.warc.gz"}`

`path-index.txt` is at `/web-archiving-stacks/data/indexes/path/path-index.txt`

cdxj indexes are in `/web-archiving-stacks/data/indexes/cdxj`

**Comment by edsu** [comment]
Since we are switching to using a relative path in the CDXJ #491 we no longer need to audit the completeness (or uniqueness) of the `path-index.txt`.
