### ISSUE TITLE
Puppeteer screenshots of PDFs do not work

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was_robot_suite#478]
It appears that puppeteer and Chromium are incapable of generating a screenshot of a PDF:

https://stackoverflow.com/a/56116056/324921

You can see the result of this failure in this SDR item:

https://argo-stage.stanford.edu/view/druid:xy437cj3892

From @peterchanws' comments (see below) we know that thumbnails for PDFs on the web is a use case we would like to support, especially for Government Documents.

The suggestion for us to try first is:

1. Modify `script/screenshot.js` to catch the `net::ERR_ABORTED` exception that is thrown when Puppeteer tries to render a PDF URL, and call a new function `screenshotPDF`.
2. Create a function `screenshotPDF` that does something like what is outlined in [this suggestion](https://stackoverflow.com/a/70437748/324921) to use PDF.js and an HTML template populated with the PDF URL, load that HTML with Puppeteer, and take the screenshot. (you will need to add PDF.js and EJS to the package.json to ensure those are installed).
3. It is important to allow any subsequent exceptions to halt the program, since there are likely to  be other types of errors that should not be masked/hidden.

If this turns out to be infeasible another option would be to download the PDF and use an image processing library like [imagemagick](https://stackoverflow.com/questions/12614801/how-to-execute-imagemagick-to-convert-only-the-first-page-of-the-multipage-pdf-t) to convert the first page to an image, but it would probably be best to try to use Puppeteer if we can first.

**Comment by lwrubel** [comment]
Question for @peterchanws: are thumbnails for PDFs currently generating correctly? If not, how high of a priority is this to set up screencapture of PDFs for seeds?

**Comment by edsu** [comment]
If you want to see the error you can run script/screnshot.js on the command line with the "frameless" URL to snapshot the PDF itself (not the addition of `mp_` to the URL):

```
$ node scripts/screenshot.js https://was-pywb-prod.stanford.edu/was/20200424061217mp_/http://www.zjredcross.org.cn//3wr/ps/webDisk/1/upload/PDF/20170505083842681.pdf screenshot.jpg
net::ERR_ABORTED at https://was-pywb-prod.stanford.edu/was/20200424061217mp_/http://www.zjredcross.org.cn//3wr/ps/webDisk/1/upload/PDF/20170505083842681.pdf
```

**Comment by edsu** [comment]
It would be interesting to run a report to see how many PDF Web Archive Seed Objects we have.

**Comment by edsu** [comment]
Good point, we won't know without doing a GET to swap.stanford.edu. I guess I was thinking we could see which Seed Objects (if any) have a label that ends in `.pdf` ?

**Comment by jcoyne** [comment]
@edsu I don't think that a file extension is going to be sufficient to determine whether something is a PDF or not. A server could return a PDF for any URL.

**Comment by edsu** [comment]
To get an exact count you can:

1. Query the db (or DSA API?) to get all the labels (URLs) for Web Archive Seed Objects.
2. GET https://was-pywb-prod.stanford.edu/was/cdx?output=json&url={url}
3. Iterate through the lines of JSON to see what the `mime` is for the first object that `status` of `200` where `mime` isn't `warc/revisit`.

There are only 5,144 so it shouldn't take too long.

**Comment by peterchanws** [comment]
@edsu Sorry, somehow I missed this issue. There are many examples of PDF as seed objects in Government sites.

**Comment by edsu** [comment]
No worries @peterchanws it was in our backlog and we just recently moved it to ready. It is good to know that we do anticipate wanting to support PDF sees, so there's no real need to count them (re: @jcoyne's questions above).

**Comment by peterchanws** [comment]
From James:
This is a special collection (California Law Enforcement Agencies SB978 Websites collection) in which Krisk was specifically wanting to collect police manuals. Most of these are PDFs. Looks like she did 2 collections, 1 for the SB978 websites (https://partner.archive-it.org/159/collections/16422/) and one for the policy manuals (https://partner.archive-it.org/159/collections/15880)

**Comment by edsu** [comment]
Thanks for the feedback @peterchanws. It is helpful to know that this is an important use case to cover. I've updated the description with a preferred first approach to fixing the underlying problem.
