### ISSUE TITLE
Run audit for all WRA collections

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was_robot_suite#485]
We need run the `rake audit[collection_druid]` task in prod and report the results here for @peterchanws and @andrewjbtw. If it's easier to adjust the rake task to audit all the collections instead of running them individually by hand that is acceptable.

**Comment by edsu** [comment]
I noticed these and thought they might be related? https://app.honeybadger.io/projects/63547/faults/86369586

**Comment by justinlittman** [comment]
[AIT Audit.xlsx](https://github.com/sul-dlss/was_robot_suite/files/8996952/AIT.Audit.xlsx)

**Comment by justinlittman** [comment]
Yes, @edsu. One of the collections is returning 500 from AIT.
