### ISSUE TITLE
Use relative path in CDXJ files

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was_robot_suite#491]
Since we are not guaranteeing the uniqueness of WARC filenames in WAS-Registrar-App's "One Time Registration" we need the CDXJ file to record the path to the WARC files it is referencing. See https://github.com/sul-dlss/was-pywb/issues/71 for more context. This can be achieved by updating the call to `cdxj-indexer` to include the `--dir-root /web-archives-stacks/data/collections` option, which will cause the WARC filename that is recorded to be relative to that location, and will include the druid tree.

**Comment by mjgiarlo** [comment]
@edsu do you think this should block the switch-over or can it go in the non-critical epic?

**Comment by edsu** [comment]
I think it can go in non-critical for thr switch. It is critical for post switch though.
