### ISSUE TITLE
robots: update devops operations concerns document

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#50]
I started one, but it needs some love.

it may make sense to splat out in a README some info about all the robots under a new 'project' of 'robots' in the devops docs ...whatever makes sense.  But the was_robot_suite under web-archiving in devopsdocs needs some love ...

**Comment by drh-stanford** [comment]
PR https://github.com/sul-dlss/DevOpsDocs/pull/129 is ready for review
