### ISSUE TITLE
write a spec for was_thumbnail_generator screenshot method

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#510]
it uses our `screenshot.js` ... and it should be possible to run that javascript code against a mocked response from wayback (a warc??)  and then use Tony Calavano's method of comparing images to ensure that the javascript code produced the expected image (see tests for `.resize_jpeg` for that image comparison.

Background:

There is no test that executes `screenshot.js`. I tried a bit yesterday to get rspec to be able to run the script and ensure it came back with the desired image.  I failed.

I wrote sul-dlss/infrastructure-integration-test/pull/451 which adds a was-seed accession to the web archive integration test … but it seems like there should be a way to test the `.screenshot` method in the thumbnail generator service class … as part of the was-robot-suite.

FYI, here is the commit that switched us to `screenshot.js` utilizing chrome headless browser, no longer using phantom.js (yay)  https://github.com/sul-dlss/was_robot_suite/commit/12f2ace3955853c607939c2cc63c1a74fe963481

**Comment by ndushay** [comment]
JCoyne says:
> I'm just hung up on the request for "a mocked response from wayback".  I have no idea how you implement that.

presumably we make an http request to a wayback machine (pywb) and something comes back … and we could store that response and feed it to the script for the test

**Comment by justinlittman** [comment]
VCR?

**Comment by ndushay** [comment]
The way this code works:

ruby launches a node program, which launches headless chrome to get a response from wayback, and then the node program we wrote uses chrome to grab a screenshot of the http response.  

The previous test used VCR to do this with phantomjs code ... but we ditched the VCR cassette.  

The old test code, with the non-existent VCR cassette:

```
 describe '.screenshot' do
    before do
      FileUtils.rm 'tmp/test_capture.jpeg', force: true
    end
    after do
      FileUtils.rm 'tmp/test_capture.jpeg', force: true
    end
    it 'captures jpeg image for the first capture of url', :image_prerequisite do
      pending 'fails from jquery error'
      VCR.use_cassette('slac_capture') do
        wayback_uri = 'https://swap.stanford.edu/20110202032021/http://www.slac.stanford.edu'
        temporary_file = 'tmp/test_capture'
        result = described_class.screenshot(wayback_uri, temporary_file)
        expect(result).to eq('')
      end
    end
  end
```

**Comment by ndushay** [comment]
@justinlittman:   do you have ideas on how we could test this?  I was thinking that we could use a fixture response from wayback (like VCR does .. but who knows when that was pulled out of this code) and hook up whatever is needed so rspec can execute a js test with headless chrome and our screenshot.js.  I was trying to figure this out and decided it should be a ticket.

**Comment by justinlittman** [comment]
Oh never mind. The retrieval from swap is performed by `screenshot.js` so VCR doesn't help. I have no idea how to test this.
