### ISSUE TITLE
Error: thumbnail-generator 

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was_robot_suite#518]
Got Error: thumbnail-generator when I tried to regenerate thumbnails by adding "wasSeedPreassemblyWF" workflow to the following druids:
https://argo.stanford.edu/view/druid:fm384yw9015
https://argo.stanford.edu/view/druid:mh176fs6925

**Comment by lwrubel** [comment]
Thumbnail generation in QA seems to be looking to a URL without `/was/`. See thumbnail here: 
https://argo-qa.stanford.edu/view/druid:gs860dm4319
