### ISSUE TITLE
deploy robots to new was robot VMs in production

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/was_robot_suite#52]
- [x] fire up was-robots1-prod VM with same recipe as stage
- [x] turn off (undeploy) from sul-robots3-prod
  - [x] disable nagios alerts and in puppet
  - [x] turn off robots (i.e., controller stop; controller quit)
  - [x] rename to `.old` directory
- [x] deploy to was-robots1-prod
  - [x] migrate CDX files to new partition and mount (see https://github.com/sul-dlss/web-archiving/issues/22)
  - [x] migrate NFS mounts of /web-archiving-stacks to sul-robots*-prod (see SAR-3358)
- [x] update the wayback VMs to use the new CDX index mounts

**Comment by tallenaz** [comment]
@drh-stanford : I verified that the puppet code for prod is the same as for `-stage`.

**Comment by tallenaz** [comment]
docs for how to turn off robots in robot master wiki
