### ISSUE TITLE
Stalled workflows (CDX indexing)

### ISSUE THREAD

**Issue by edsu** [sul-dlss/was_robot_suite#520]
Argo [lists](https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=wasCrawlDisseminationWF%3Acdx-generator%3Aerror) 84 items that are stuck in the CDX indexing stage from the OpenWayback days.

It would be good to ensure that:

1. The content is how available in swap.stanford.edu (since we reindexed everything as part of the migration to pywb).
2. The `wasCrawlDisseminationWF` shows up as completed in Argo.

The 84 items are available as [JSON](https://argo.stanford.edu/catalog?f[wf_wps_ssim][]=wasCrawlDisseminationWF%3Acdx-generator%3Aerror&per_page=100&format=json) from Argo if that helps with diagnosing or addressing the problem.

It would be good to select a few of the WARC files and confirm if we can reproduce the error with the old Java CDX indexing and see CDX indexing work with cdxj-indexer (which we are now using).

One thing I noticed when looking at these is that they largely (78/84) are `.arc.gz` files instead of `warc.gz` files. Also there’s a set of WARCs where the *source-id* has a pattern with `BDFL` in it like: `sul:BDFL-WARCFiles-g-l` which may be WARCs converted from HTTrack.

**Comment by edsu** [comment]
I got the 84 druids out of the Argo JSON results, and wrote a one-off program to look through the CDX index to see if any of those druids are present.  It's running now and I'll report back:

https://gist.github.com/edsu/2d80da5b1956ccac54dea197ee416507

**Comment by edsu** [comment]
It appears that all the druids that previously encountered errors during CDX indexing are now present in the index EXCEPT for these from the Stanford University Archives collection:

* mv300dt6569
* mk879xr0461
* dn752dz0508

I will manually index these and add to the`level0.cdxj`.

**Comment by edsu** [comment]
It looks like the data for [mk879xr0461](https://argo.stanford.edu/catalog?search_field=text&q=mk879xr0461) is no longer present on `/web-archiving-stacks/data/collections/`. It also looks like the item has no content files in Argo, so I guess that makes sense? @peterchanws is it ok to ignore this one?

**Comment by edsu** [comment]
mv300dt6569 and dn752dz0508 have been indexed manually and merged into level0.cdxj

**Comment by peterchanws** [comment]
@edsu It's fine to ignore this one.

**Comment by edsu** [comment]
I experimented in QA with setting the workflow steps to completed in reverse order and that seemed to allow the item to have its error cleared and for no changes to happen to the CDX and CDXJ indexes.

I tried with one in production: https://argo.stanford.edu/view/druid:bj330fg0526

Now there are 83 more to do :-)

**Comment by edsu** [comment]
These errors have all been cleared except for this one:

https://argo.stanford.edu/view/druid:sd725cc2793

The workflow steps don't have any errors associated with them. @andrewjbtw @apchan do you have any idea what we should do with this one?

**Comment by lwrubel** [comment]
Tagging @peterchanws

**Comment by andrewjbtw** [comment]
Could the exclamation points and the `@` symbol in some of the filenames have anything to do with the issue?

**Comment by edsu** [comment]
There are no workflows stuck in CDX indexing now.
