### ISSUE TITLE
Thumbnail-generator error 

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was_robot_suite#522]
Thumbnail-generator error 
https://argo.stanford.edu/view/druid:sj146gq6843

Here is the link to the site in AIT
https://wayback.archive-it.org/16422/20210415032529/https://coronado.ca.us/cms/One.aspx?portalId=746090&pageId=1602773

**Comment by peterchanws** [comment]
I re-run all druids (~55) with thumbnail-generator error Argo. 26 still have thumbnail-generator error
https://argo.stanford.edu/catalog?f%5Bwf_wps_ssim%5D%5B%5D=wasSeedPreassemblyWF%3Acontent-metadata-generator&f%5Bwf_wps_ssim%5D%5B%5D=wasSeedPreassemblyWF%3Athumbnail-generator%3Aerror&per_page=50

**Comment by lwrubel** [comment]
#478 and #529 will address a good proportion of these.

**Comment by lwrubel** [comment]
@peterchanws Once we've deployed to production with the weekly dependency updates, would you re-try the remaining seeds needing thumbnails?

**Comment by lwrubel** [comment]
No, it has to go out to QA and stage first. @edsu is sharing in Slack when the deploys will happen and we'll highlight that for you too.

**Comment by peterchanws** [comment]
@lwrubel Thanks.

**Comment by lwrubel** [comment]
Closing since the running with the bugfix worked and there are reasons for the remaining four failing that are not related to the thubmnail-generator code.
