### ISSUE TITLE
thumbnail-generator step in wasSeedPreassembly is filling up /tmp

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was_robot_suite#526]
On was-robots-prod1, `/tmp` has filled up. There were 1,372 directories called `puppeteer_dev_chrome_profile-xxxxx` (e.g. `puppeteer_dev_chrome_profile-ri21fp`). The earliest is from July 6, 2022. It looks like puppeteer is leaving stuff behind in `/tmp` when a thumbnail is generated and it doesn’t get cleared out.

Review the thumbnail-generator step and puppeteer set-up to determine how to clean up after a screenshot is generated.

**Comment by ndushay** [comment]
For te record, assembly-image jp2 generation creates a temporary tiff, and also cleans it up after -- there are specs in the gem showing the temporary tiff is removed.  But by all means check inside directories and see what is there -- it could be straight up was-robot code not playing nicely ...

**Comment by ndushay** [comment]
do we also need the puppeteer tmp dir to be cleaned out so it doesn't fill up eventually?

**Comment by mjgiarlo** [comment]
@ndushay When the `Dir.mktmpdir` block closes, Ruby will remove it, so I think we should be good to go.
