### ISSUE TITLE
encode url param in CDX API queries

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was_robot_suite#529]
When the wasSeedPreassembly thumbnail-generator step looks up a URL via the CDXJ API, the url param should be encoded. Otherwise, the step fails with something like:

```
thumbnail-generator : Thumbnail for druid druid:cd458dc6846 and https://citydocs.cityoforange.org/OrangePD/Browse.aspx?id=61300&repo=OrangePD&cr=1 can't be generated. https://citydocs.cityoforange.org/OrangePD/Browse.aspx?id=61300&repo=OrangePD&cr=1 not found in cdxj index. 
```
([example seed #1](https://argo.stanford.edu/view/druid:cd458dc6846), [example seed #2](https://argo.stanford.edu/view/druid:kq065dr3806))

CDX queries should look like:
`https://swap.stanford.edu/was/cdx?url=https%3A%2F%2Fcitydocs.cityoforange.org%2FOrangePD%2FBrowse.aspx%3Fid%3D61300%26repo%3DOrangePD%26cr%3D1`

Will need to get fixed in the thumbnail generator service:
https://github.com/sul-dlss/was_robot_suite/blob/81c68c8cb24a0da5d47355ab0612227816f08bb3/lib/dor/was_seed/thumbnail_generator_service.rb#L48

**Comment by edsu** [comment]
Nice catch!
