### ISSUE TITLE
vet prod crawl workflows (for new robot VMs)

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/was_robot_suite#53]
We have all the WAS robots deployed to production on their new VMs. we need to vet that production is working correctly by accessioning some items through the pipeline.

- [x] WAS robots deployed to was-robots1-prod
- [x] was-registrar deployed to was-registrar-prod
  - [x] dor-services-app upgraded in prod so registration works
- [x] accession seed item
- [x] accession crawl item

**Comment by drh-stanford** [comment]
Nicholas will have some items ready for production early next week

**Comment by ndushay** [comment]
@nullhandle   I *think* we want you to exercise all robots with crawl items on -stage (cdx indexing changes), then on -prod (cdx indexing changes and new robot VMs) ...  @drh-stanford   this is true, yes?

**Comment by drh-stanford** [comment]
yes, that order is correct. stage first to test the new log level CDX indexing and then we'll push that to production when it's ready and then move onto production. production is ready now, but without the new CDX indexing, so we should probably test stage first rather than having to do production twice.

**Comment by nullhandle** [comment]
Confirmed that both seed and crawl accessioning workflows are working in production.
