### ISSUE TITLE
Remove path dirs from web-archiving-stacks

### ISSUE THREAD

**Issue by lwrubel** [sul-dlss/was_robot_suite#532]
We are not using a path index for pywb, so to avoid confusion, remove:

`/web-archiving-stacks/data/indexes/path`
`/web-archiving-stacks/data/indexes/path-working`

The existing path-indexer step is still writing to these directories even though we're not using the path, so when the deploy removes the path-indexer step it will be safe to remove them.

**Comment by mjgiarlo** [comment]
Done in all envs.
