### ISSUE TITLE
when re-running the wasSeedPreassemblyWF, do not use the Cocina label to generate the seed URL in the descriptive metadata

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/was_robot_suite#544]
The wasSeedPreassemblyWF generates descriptive metadata based on the value entered in the "label" field on the registration form. This value makes its way into two fields in Cocina:

- the "label" field (the one that's a legacy of Fedora having an object label
- the descriptive metadata

The wasSeedPreassemblyWF should use the seed URL as found in the descriptive metadata to do things like generate thumbnails. @peterchanws has found that the the workflow is actually using the Cocina "label" for this purpose.

The problem with using the Cocina label is that it cannot be changed after registration. This was possible in the old system via direct XML editing but in the new system we've moved away from using the cocina label and may remove the field entirely. This usage for seed thumbnails is one that we missed during both the migration and the recent workcycle, and seems to be related to the way this workflow still follows the old SDR convention of creating a descriptiveMetadata.xml file.

**User impact**

It's not possible to rerun thumbnail generation by rerunning the workflow if the seed URL has to be changed to include "http://", for example. The thumbnail generation will continue to look at whatever URL was originally put in the label, even if the URL was changed in the descriptive metadata. 

This means that the druid has to be purged or decommissioned and replaced by a newly-registered druid. It would be much more convenient to be able to re-run seedPreassembly on the existing druid after fixing the URL.

**Comment by lwrubel** [comment]
@andrewjbtw and @peterchanws I've got a branch which looks in the following places for the thumbnail URI:

1) description.note where the note has a displayLabel of "Original site". This would normally get created when a seed is successfully accessioned. It could also be added to the description metadata later via upload.
2) description.title since title and label are all that contain the URL when a new seed is being created. If the title has "Web Archive Seed for" already added, it won't get used.
3) fall back to label

Does this match what you'd like to see happen?

**Comment by jcoyne** [comment]
@lwrubel do we need to have the fallback?  I find that code for things like this is hard to maintain in the long term, and we might be better served by fixing all the data now and not having to support a rarely (or never) used code path.

**Comment by jcoyne** [comment]
@andrewjbtw could we change the registration form on Argo to better support this when the user selects "Content type: webarchive-seed"?

**Comment by edsu** [comment]
Updating the registration process will definitely help with workflows moving forward, but without data remediation I don't think it will help with re-running already registered webarchive-seed objects?

**Comment by lwrubel** [comment]
I like the idea of improving registration. It's very easy to make a mistake setting up a seed. 

I think we do still need to have a way to fix or update a URL, which was the intent here. @jcoyne in the meantime would you recommend that the thumbnail generator raise an error in that rarer case and not fall back to the label?

**Comment by jcoyne** [comment]
Yeah, I think "No URL found in the description.note or description.title" would be good.

**Comment by lwrubel** [comment]
@andrewjbtw wanted to bring this one to your attention before I merge and close the PR (#547). If you'd like to see if deployed, I can do that. The seed URI will be taken from descriptive metadata fields:

1.  description.note where the note has a displayLabel of "Original site". This field gets created when a seed is successfully accessioned. It could also be added to the description metadata later via upload.
2. description.title (gets initially populated from the label at registration)

**Comment by andrewjbtw** [comment]
I'm definitely in favor of finding a way to improve registration to address this, but remediation alone can't fix it as long as it's possible to create new items with this issue.
