### ISSUE TITLE
wasPreassemblyWF not using new descriptive metadata 

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was_robot_suite#560]
I tried to update descriptive metadata in a seed: "Original site" from "www.hoor-al-ayn.com/lectures/anwar-al-awlaki" to "https://www.hoor-al-ayn.com/lectures/anwar-al-awlaki"  https://argo.stanford.edu/view/druid:mt944hv0192

I downloaded the Cocina spreadsheet, changed the "Original site" from "http://www.hoor-al-ayn.com/lectures/anwar-al-awlaki" to "https://www.hoor-al-ayn.com/lectures/anwar-al-awlaki", system shown "Descriptive metadata has been updated." Then, re-run wasSeedPreassemblyWF. Somehow, nothing changed. I downloaded the Cocina spreadsheet and found the  "Original site" is still  "http://www.hoor-al-ayn.com/lectures/anwar-al-awlaki"

**Comment by mjgiarlo** [comment]
@peterchanws I can make time this week to take a look if you have time to pair. Let me know when works best for you, Peter?

**Comment by edsu** [comment]
@peterchanws I was trying to replicate this on argo-qa and wasn't able to. Here are the steps I followed with https://argo-qa.stanford.edu/view/druid:bh850dg9729:

1. I went to https://argo-qa.stanford.edu/view/druid:bh850dg9729 and clicked `Manage Description` then `Download Cocina spreadsheet`.
2. I opened the `descriptive-bh850dg9729.csv` and changed the `title1` column from `Web Archive Seed for https://webrecorder.net` to `Web archive seed for https://webrecorder.net`, and saved it.
3. I then reuploaded the CSV by clicking on `Bulk Actions`, `New Bulk Action`, and selecting `Upload Descriptive Metadata Spreadsheet`.
4. The title was changed.

Can you confirm that QA is working for you too? If it is then we can look and see if there is something specific about the item you are working with in production. https://argo.stanford.edu/view/druid:mt944hv0192

**Comment by peterchanws** [comment]
@edsu The field I want to change is column T "note1.value". I tried that using https://argo-qa.stanford.edu/view/druid:bh850dg9729. Change note1.value from https://webrecorder.net to webrecorder.net; upload the Cocina spreadsheet and column T "note1.value" remain as https://webrecorder.net - no change. The use case is usually the opposite - try to add "https://" to content in "note1.value".

**Comment by edsu** [comment]
@peterchanws I'm confused. I just downloaded the spreadsheet for https://argo-qa.stanford.edu/view/druid:bh850dg9729 and updated the the `note1.value` column to `THIS IS A TEST`, then uploaded it, and then redownloaded it and see that the `note1.value` is correctly set to `THIS IS A TEST`.

Is the problem that re-running `wasSeedPreassemblyWF` should be doing something with this updated `note1.value` and it is not?

**Comment by peterchanws** [comment]
@edsu The problem lead to this issue is that some web seeds were accessioned with label NOT with http/https preffix. This will cause the improper accession of web seed and no link to archived site appear in the purl page. I have just created https://argo-stage.stanford.edu/view/druid:df402tw5976 with "www.theaaas2020project.com" as label. As expected, no link to archived site appear in the purl page. I changed the label (note1.value) from "www.theaaas2020project.com" to "https://www.theaaas2020project.com". I believe this update the label and will correct the missing  link to archived site appear in the purl page. However, the problem remain. Should we have a quick chat via huddle?

**Comment by peterchanws** [comment]
I registered another item using "https://www.theaaas2020project.com/" as label. Links to archived site appear in the purl page
https://argo-stage.stanford.edu/view/druid:zm299qr5262

**Comment by edsu** [comment]
I got some help pairing with @lwrubel this morning and we noticed that the sul-embed code is [querying](https://github.com/sul-dlss/sul-embed/blob/fe1092dce09986f83ae668c1ba8624070bcab0c7/app/viewers/embed/viewer/was_seed.rb#L24-L26) for `//mods:url[@displayLabel="Archived website"]` to generate the Timemap URL in SWAP to fetch the snapshots that available:

For the SDR object you originally posted about ([druid:mt944hv0192](https://argo.stanford.edu/view/druid:mt944hv0192)) the [MODS XML](https://purl.stanford.edu/mt944hv0192.mods) has:

```xml
<url displayLabel="Archived website">https://swap.stanford.edu/*/www.hoor-al-ayn.com/lectures/anwar-al-awlaki
</url>
```

The sul-embed code then [constructs](https://github.com/sul-dlss/sul-embed/blob/fe1092dce09986f83ae668c1ba8624070bcab0c7/app/viewers/embed/viewer/was_seed.rb#L33) the Timemap URL by replacing the `*` with `timemap` resulting in:

https://swap.stanford.edu/timemap/www.hoor-al-ayn.com/lectures/anwar-al-awlaki

Which does not return any results. But adding the `http://` protocol (as you have been trying to do by updating the Cocina) works:

https://swap.stanford.edu/timemap/http://www.hoor-al-ayn.com/lectures/anwar-al-awlaki

We noticed that you probably will want to be updating the Cocina Spreadsheet and changing the `access.url1.value` column from `https://swap.stanford.edu/*/www.hoor-al-ayn.com/lectures/anwar-al-awlaki` to `https://swap.stanford.edu/*/http://www.hoor-al-ayn.com/lectures/anwar-al-awlaki`.

Could you give that a try and see if this results in the snapshots appearing correctly in PURL and SearchWorks?

**Comment by peterchanws** [comment]
Thanks, Ed./Laura It works.
