### ISSUE TITLE
robots: add nagios checks for mounted dirs, etc.

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#60]
after our discoveries yesterday in trying to accession on the new robot VMs, it seems prudent to add nagios checks for directories in 

- https://github.com/sul-dlss/shared_configs/blob/was-robots1-prod/config/environments/production.rb

Also
- cert checks
- http checks to those services?

This may help us spot when robots break a LOT better.

**Comment by drh-stanford** [comment]
I've added directory checks via `check_file_age` in https://github.com/sul-dlss/puppet/pull/1503

**Comment by drh-stanford** [comment]
I've added a redis check too.

The certs aren't used for https but rather for authentication to DOR, so I just put a check for their existance.

Note that this implementation is less than ideal because we have the same configuration information both in puppet and shared_configs.

**Comment by ndushay** [comment]
Did we decide to add check_http for dor_services_app or is this done?

**Comment by drh-stanford** [comment]
no this is done.
