### ISSUE TITLE
upgrade node engine to version 16 or higher on VMs 

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#600]
See PR #599 re: pinning pdfjs-dist  to a version that works with node 14 to avoid this deploy time error:

```
error pdfjs-dist@3.5.141: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.19.3"
```

If we upgrade node on the VMs, we should also adjust package.json to use the more recent distribution of pdfjs-dist.

**Comment by lwrubel** [comment]
Closed with https://github.com/sul-dlss/was_robot_suite/pull/726, allowing js dependencies to float up (node on the VM is now current).
