### ISSUE TITLE
pdfjs-dist is pinned to 3.4.120

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/was_robot_suite#601]
we don't usually pin to an exact version;  this happened in PR #599, which came about due to a failed deploy:

```
error pdfjs-dist@3.5.141: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.19.3"
error Found incompatible module.
yarn stderr: Nothing written
```

Ticket #600 is about upgrading node on the was-robots VMs to allow a more recent version of pdfjs-dist;  this ticket is about changing the constraints in `package.json` to be `"^3.4.120"` (?)  rather than `"3.4.120"`

Note that #525 is the PR that added pdfjs-dist to this repo, and therefore shows the specific test(s) added.

**Comment by lwrubel** [comment]
Closed with https://github.com/sul-dlss/was_robot_suite/pull/726, allowing js dependencies to float up.
