### ISSUE TITLE
Thumbnail-generator failed for Archived PDF

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was_robot_suite#632]
Thumbnail-generator failed for Archived PDFs. Here are some examples.

https://wayback.archive-it.org/11377/20181120231702/http://sanjoseca.gov/DocumentCenter/View/79270/
https://argo.stanford.edu/view/druid:xf486tv1811

https://wayback.archive-it.org/11377/20181120232022/http://sanjoseca.gov/DocumentCenter/View/79489/
https://argo.stanford.edu/view/druid:jx955fc4548

https://wayback.archive-it.org/11377/20181120231857/http://sanjoseca.gov/DocumentCenter/View/79490/
https://argo.stanford.edu/view/druid:rw413vg3881

**Comment by edsu** [comment]
Ah, it looks like the problem here is our fallback code for screenshotting PDFs relies on the URL ending in `.pdf`.

https://github.com/sul-dlss/was_robot_suite/blob/main/scripts/screenshot.js#L36

I'm going to relax this constraint and allow it to fall back to embedding with pdf.js whenever the 'net:::ERR_ABORTED' error  is encountered. Hopefully that won't turn out to be too lenient...

**Comment by peterchanws** [comment]
Thanks, Ed. Let me know when the the fix is available.

**Comment by peterchanws** [comment]
Some how this is fine https://purl.stanford.edu/dh030gb2311

**Comment by edsu** [comment]
@peterchanws yes, that's because the URL has a `pdf` in it: https://www.losaltosca.gov/sites/default/files/fileattachments/city_clerk/page/46821/argument_for.pdf

**Comment by peterchanws** [comment]
I see. I will regenerate the thumbnails for the druid having problems. Thanks again for the quick actions.

**Comment by peterchanws** [comment]
I have regenerated the thumbnails for the 2 druids mentioned in the issue and all regeneration failed.

**Comment by lwrubel** [comment]
It looks like the fix for this issue is not yet deployed to production. That has to go out with other production deployments, probably later today, but possibly tomorrow. We can let you know when the new code is deployed.

**Comment by peterchanws** [comment]
Thanks, Laura.

**Comment by edsu** [comment]
@peterchanws the fix has been deployed, do you want to give it another try?

**Comment by peterchanws** [comment]
Thanks, Ed. Thumbnails generated properly for the 3 cases quoted.
