### ISSUE TITLE
Error: thumbnail-generator

### ISSUE THREAD

**Issue by peterchanws** [sul-dlss/was_robot_suite#636]
https://argo.stanford.edu/view/druid:bb192ns2865
Error: thumbnail-generator : Thumbnail for druid druid:bb192ns2865 and https://www.smcacre.org/sites/main/files/file-attachments/fostercityresno65_66.pdf can't be generated. https://www.smcacre.org/sites/main/files/file-attachments/fostercityresno65_66.pdf not found in cdxj index.

https://argo.stanford.edu/view/druid:bb584wb8859
Error: thumbnail-generator : Thumbnail for druid druid:bb584wb8859 and https://www.facebook.com/Saleh4CUHSD/ can't be generated. https://www.facebook.com/Saleh4CUHSD/ not found in cdxj index.

https://argo.stanford.edu/view/druid:bd109zd7221
Error: thumbnail-generator : Thumbnail for druid druid:bd109zd7221 and https://www.facebook.com/suvarnaforschoolboard/ can't be generated. https://www.facebook.com/suvarnaforschoolboard/ not found in cdxj index.

https://argo.stanford.edu/view/druid:bj188rk8618
Error: thumbnail-generator : Thumbnail for druid druid:bj188rk8618 and https://www.facebook.com/smadhathil/ can't be generated. https://www.facebook.com/smadhathil/ not found in cdxj index.

https://argo.stanford.edu/view/druid:bk992nz7373
Error: thumbnail-generator : Thumbnail for druid druid:bk992nz7373 and https://www.facebook.com/YvonneForMorganHill/ can't be generated. https://www.facebook.com/YvonneForMorganHill/ not found in cdxj index.

https://argo.stanford.edu/view/druid:bm083by8379
Error: thumbnail-generator : Thumbnail for druid druid:bm083by8379 and https://www.smcacre.org/sites/main/files/file-attachments/33_eng_mhh_ia.pdf can't be generated. https://www.smcacre.org/sites/main/files/file-attachments/33_eng_mhh_ia.pdf not found in cdxj index.

https://argo.stanford.edu/view/druid:bm124vf3311
Error: thumbnail-generator : Thumbnail for druid druid:bm124vf3311 and https://www.facebook.com/rosa4ssfcityclerk/ can't be generated. https://www.facebook.com/rosa4ssfcityclerk/ not found in cdxj index.

**Comment by edsu** [comment]
The error message is saying that the URL is not in SWAP. Were you expecting the content to be available. Lets take this one as an example:

https://www.facebook.com/suvarnaforschoolboard/

Should that be in SWAP? Do you know which crawl object it should be in? Maybe we have an indexing problem?

**Comment by edsu** [comment]
I took a look in the WARC data for `druid:qj641jj9444` and only found the following www.facebook.com URLs that were crawled:

```
was@was-robots1-prod:/web-archiving-stacks/data/collections/pr394nk1057/qj/641/jj/9444$ gunzip -c *.gz | grep --text 'WARC-Target-URI: https://www.facebook.com' | uniq

WARC-Target-URI: https://www.facebook.com/robots.txt
WARC-Target-URI: https://www.facebook.com/pages/category/Political-Candidate/Marie-Blankley-for-Gilroy-City-Council-1764811583537116/
WARC-Target-URI: https://www.facebook.com/robots.txt
WARC-Target-URI: https://www.facebook.com/harneyforcouncil/
WARC-Target-URI: https://www.facebook.com/login/device-based/regular/login/?login_attempt=1&amp;lwv=110
```

Sure enough, you can see one of these in SWAP: https://swap.stanford.edu/was/20181120231619/https://www.facebook.com/harneyforcouncil/

I don't think I can see `ait-11377-2018_11` on Archive-It can I?

**Comment by peterchanws** [comment]
I checked the reported links in AIT and ALL were not archived. Sorry for the trouble. 

https://argo.stanford.edu/view/druid:bb192ns2865
https://www.smcacre.org/sites/main/files/file-attachments/fostercityresno65_66.pdf
AIT: This page has not been archived here

https://argo.stanford.edu/view/druid:bb584wb8859
https://www.facebook.com/Saleh4CUHSD/ 
AIT: This page has not been archived here

https://argo.stanford.edu/view/druid:bd109zd7221
https://www.facebook.com/suvarnaforschoolboard/ 
AIT: This page has not been archived here

https://argo.stanford.edu/view/druid:bj188rk8618
https://www.facebook.com/smadhathil/ 
AIT: This page has not been archived here

https://argo.stanford.edu/view/druid:bk992nz7373
https://www.facebook.com/YvonneForMorganHill/ 
AIT: This page has not been archived here

https://argo.stanford.edu/view/druid:bm083by8379
https://www.smcacre.org/sites/main/files/file-attachments/33_eng_mhh_ia.pdf 
AIT: This page has not been archived here

https://argo.stanford.edu/view/druid:bm124vf3311
https://www.facebook.com/rosa4ssfcityclerk/ 
AIT: This page has not been archived here
