### ISSUE TITLE
deploy robots to prod (all but non-AIT seeds working!) - and watch the queue for problems

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/was_robot_suite#8]
A new deploy will:

* configure the robots properly to use latest dor-services and lyber-core and robot-controller gems, in line with other robots.  (Make it work, and pay tech debt.)
* combine 5 codebases and 5 deploys into a single codebase with a single deploy for better maintenance and troubleshooting.  Allowed us to apply fixes ONCE instead of 5 times.
* added wait for seed sourcexml as workflows wasn't getting druid back to was-registrar in time for seed workflow to use it.

**Comment by ndushay** [comment]
blocked by

**Comment by ndushay** [comment]
turned off nagios notifications for old robots (yay);  turned off robots in prod box;  moved old robots dirs to was-OLD ...   so ready for new deploy.

**Comment by drh-stanford** [comment]
Here's what is in the queues in prod right now:

![screen shot 2016-07-05 at 11 45 05 am](https://cloud.githubusercontent.com/assets/1861171/16595847/f6d1b87c-42a5-11e6-9a84-10827a30ce7e.png)
